services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:3180'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - 4567:4567
      - 3180:3180
      - 2222:22
    volumes:
      - /path/to/etc:/etc/gitlab
      - /path/to/logs:/var/log/gitlab
      - /path/to/opt:/var/opt/gitlab
    networks:
      - gitlab_net

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /path/to/gitlab-runner/dir:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_net
    dns:
      - 127.0.0.1

networks:
  gitlab_net: